// swift-tools-version: 5.9
//
// Swift Package Manager manifest for kmp-ai.
//
// Distributes two binary frameworks alongside the Maven Central artifacts:
//   - KmpAI.xcframework      — Swift-callable bindings for the kmp-ai LLM API
//                              (LlmEnvironment, LlmEngine, ModelSource, …)
//   - llama.xcframework      — llama.cpp + ggml dylibs (b6817), transitively
//                              required by KmpAI at runtime
//
// Both URLs point to assets attached to the matching GitHub Release. The
// checksums below are written by `scripts/release-spm.sh` on each release —
// do not edit by hand.
//
// Consume from your iOS app:
//
//   // Package.swift
//   .package(url: "https://github.com/fadizg/kmp-ai", exact: "0.3.0")
//
//   // Then in target dependencies:
//   .product(name: "KmpAI", package: "kmp-ai")
//
// In Swift code:
//
//   import KmpAI
//   let env = LlmEnvironmentCompanion.shared.default()
//   // env.load(source:config:completionHandler:) …
//
// Note: the binary names are prefixed with `KAI` in the generated Obj-C
// headers (e.g. `KAILlmEnvironment`). The Swift names drop the prefix
// thanks to `swift_name` annotations — use `LlmEnvironment` directly.

import PackageDescription

// ── release coordinates (autogenerated — do not edit by hand) ────────────
let releaseTag = "0.0.0-PLACEHOLDER"
let kmpAIChecksum = "0000000000000000000000000000000000000000000000000000000000000000"
let llamaChecksum = "0000000000000000000000000000000000000000000000000000000000000000"
// ─────────────────────────────────────────────────────────────────────────

let releaseBaseURL = "https://github.com/fadizg/kmp-ai/releases/download/v\(releaseTag)"

let package = Package(
    name: "kmp-ai",
    platforms: [
        .iOS(.v14),
    ],
    products: [
        .library(name: "KmpAI", targets: ["KmpAIWrapper"]),
    ],
    targets: [
        .binaryTarget(
            name: "KmpAI",
            url: "\(releaseBaseURL)/KmpAI.xcframework.zip",
            checksum: kmpAIChecksum
        ),
        .binaryTarget(
            name: "llama",
            url: "\(releaseBaseURL)/llama.xcframework.zip",
            checksum: llamaChecksum
        ),
        // Wrapper target so `KmpAI` automatically pulls in `llama` for
        // consumers — they only declare `.product(name: "KmpAI", …)`.
        .target(
            name: "KmpAIWrapper",
            dependencies: ["KmpAI", "llama"],
            path: "spm/KmpAIWrapper"
        ),
    ]
)
